# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Notes' do
	pod 'MagicalRecord', '~> 2.2'
	pod 'MBProgressHUD', '~> 0.9'
	pod 'InfColorPicker', '~> 0.0.1'
end

target 'NotesTests' do

end

