# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'NetMusic' do
	pod "AFNetworking", "~> 2.0"
	pod 'MBProgressHUD', '~> 0.9'
	pod 'FreeStreamer', '~> 2.9.7'
end

target 'NetMusicTests' do

end

