# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'AnyNote' do
pod 'MagicalRecord', '~> 2.2'
end

target 'AnyNoteTests' do

end

